[profile.release]
debug = true

[package]
name = "wordle-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
itertools = "0.12.1"
ratatui = "0.26.1"
rayon = "1.9.0"
